apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: log-queue-scaler
  namespace: bank
spec:
  scaleTargetRef:
    kind:          Deployment                       # Optional. Default: Deployment
    name:          log-queue                  # Mandatory. Must be in the same namespace as the ScaledObject
  pollingInterval:  5                              # Optional. Default: 30 seconds
  cooldownPeriod:   30                              # Optional. Default: 300 seconds
  minReplicaCount:  1                               # Optional. Default: 0
  maxReplicaCount:  100                               # Optional. Default: 100
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://10.43.133.94:9090
      metricName: bull_queue_waiting
      threshold: '1000'
      query: bull_queue_waiting{queue="LOG_QUEUE"}