apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-queue
  namespace: bank
spec:
  replicas: 100
  selector:
    matchLabels:
      app: transfer-queue
  template:
    metadata:
      labels:
        app: transfer-queue
    spec:
      containers:
      - name: transfer-queue
        image: abdoubentegar/transfer-queue:v10
        env:
        - name: MONGO_URI
          value: "mongodb://adminuser:password123@4.233.192.179:27017/bank?authSource=admin"
        - name: REDIS_HOST
          value: "4.233.192.179"
        - name: REDIS_PORT
          value: "30355"
        - name: ELASTICSEARCH_URI
          value: "http://4.233.192.179:30546"
        - name: ELASTICSEARCH_USERNAME
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          value: "eaHmnvrTaKRuv23sye1K"